import { hashSeed, scatter, type ScatterRect } from '../helpers/seedScatter';
import { PROJECT_FOLDERS, type MediaAsset } from '../generated/mediaManifest';

/**
 * Project board configuration.
 *
 * The on-disk folders carry a leading number ("1. Events", "2. Graphic
 * Design"…). We map each folder to a stable `slug` used in the URL
 * (`/projects/events`), a display title, and category metadata that drives
 * the placeholder copy / sticker accents until Ema fills `description`.
 *
 * Per-asset board placement (x/y/rot/w in %) is generated by a deterministic
 * scatter seeded from the slug — same input → same output every time. Edit
 * the manual overrides at the bottom of this file to pin specific assets.
 */

export interface ProjectMeta {
  slug: string;
  num: number;
  folder: string;
  title: string;
  /** 'events' = renders EventText HTML; everything else = scatter board. */
  kind: 'normal' | 'events';
  /** Short copy under the title until the user provides real text. */
  description: string;
  /** Sticker accent for the board (one of three SVG icons). */
  sticker: 'printer' | 'folder' | 'paperclip';
  /** Optional pinned notes (post-it style). */
  notes?: { x: number; y: number; text: string; color: 'yellow' | 'blue' | 'pink' }[];
}

const META: Record<string, Omit<ProjectMeta, 'folder' | 'num'>> = {
  '1. Events': {
    slug: 'events',
    title: 'Events',
    kind: 'events',
    description: 'Designing experiences that get people to interact — with each other, with a space, or with an idea.',
    sticker: 'paperclip',
  },
  '2. Graphic Design': {
    slug: 'graphic-design',
    title: 'Graphic Design',
    kind: 'normal',
    description: 'Editorial, posters, brand systems and the occasional weird experiment with type and image.',
    sticker: 'folder',
  },
  '3. 3D': {
    slug: '3d',
    title: '3D',
    kind: 'normal',
    description: 'Modelling, lighting, look-dev — environments, props and short cinematic scenes.',
    sticker: 'printer',
  },
  '4. Interactive Media Technology': {
    slug: 'imt',
    title: 'Interactive Media Technology',
    kind: 'normal',
    description: 'Sensor-driven prototypes, code-as-canvas, and small physical-digital crossovers.',
    sticker: 'folder',
  },
  '5. Product Design & Brand Identity': {
    slug: 'product-and-brand',
    title: 'Product Design & Brand Identity',
    kind: 'normal',
    description: 'From early sketch to held object — and the system of marks that lives around it.',
    sticker: 'folder',
  },
  '6. Typography': {
    slug: 'typography',
    title: 'Typography',
    kind: 'normal',
    description: 'Letterforms as image. Hand-drawn, vectorised, distorted, occasionally legible.',
    sticker: 'paperclip',
  },
  '7. AI': {
    slug: 'ai',
    title: 'AI',
    kind: 'normal',
    description: 'Generative tools as a sketchbook — directing models, curating outputs, breaking the prompt.',
    sticker: 'printer',
  },
  '8. Digital Art': {
    slug: 'digital-art',
    title: 'Digital Art',
    kind: 'normal',
    description: 'Personal pieces — illustration, collage, painted-over 3D, anything that ends up on a screen.',
    sticker: 'folder',
  },
  '9. Marketing Campaigns': {
    slug: 'marketing-campaigns',
    title: 'Marketing Campaigns',
    kind: 'normal',
    description: 'Concepts, key visuals, and the connective glue that turns a moodboard into a launch.',
    sticker: 'paperclip',
  },
  '10. mp4': {
    slug: 'motion',
    title: 'Motion',
    kind: 'normal',
    description: 'Loops, fragments, music videos and short-form motion experiments.',
    sticker: 'printer',
  },
  '11. UX`UI': {
    slug: 'ux-ui',
    title: 'UX / UI',
    kind: 'normal',
    description: 'Flows, screens, micro-interactions — interfaces that try not to get in the way.',
    sticker: 'folder',
  },
  '12. Holistic Art Magazine': {
    slug: 'holistic-art-magazine',
    title: 'Holistic Art Magazine',
    kind: 'normal',
    description: 'Art-direction and editorial design across the issues of Holistic Art Magazine.',
    sticker: 'folder',
  },
  '13. Photography': {
    slug: 'photography',
    title: 'Photography',
    kind: 'normal',
    description: 'Film and digital — places, people and the in-between bits.',
    sticker: 'paperclip',
  },
  '14. Sims Custom Content': {
    slug: 'sims-cc',
    title: 'Sims Custom Content',
    kind: 'normal',
    description: 'Custom assets for The Sims — meshes, textures, tiny worlds.',
    sticker: 'folder',
  },
  '15. Projection Mapping + VJ + Lights': {
    slug: 'projection-vj-lights',
    title: 'Projection Mapping + VJ + Lights',
    kind: 'normal',
    description: 'Live visuals, multi-projector setups, and lights as a co-performer.',
    sticker: 'printer',
  },
  '16. Experimental': {
    slug: 'experimental',
    title: 'Experimental',
    kind: 'normal',
    description: 'The shelf of half-done weird things that don\u2019t fit anywhere else (yet).',
    sticker: 'paperclip',
  },
};

export interface BoardAsset extends MediaAsset, ScatterRect {}

export interface Project extends ProjectMeta {
  assets: BoardAsset[];
}

function buildProject(folderEntry: typeof PROJECT_FOLDERS[number]): Project {
  const meta = META[folderEntry.folder];
  if (!meta) {
    // Unknown folder — fallback so build doesn't break if a new folder appears
    // in public/2. Projects/.
    const slug = folderEntry.folder.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
    const numMatch = folderEntry.folder.match(/^(\d+)\./);
    return {
      slug,
      num: numMatch ? parseInt(numMatch[1], 10) : 99,
      folder: folderEntry.folder,
      title: folderEntry.folder,
      kind: 'normal',
      description: '',
      sticker: 'folder',
      assets: [],
    };
  }
  const numMatch = folderEntry.folder.match(/^(\d+)\./);
  const num = numMatch ? parseInt(numMatch[1], 10) : 99;
  // Cap displayed assets at 12 — any more clutters the board and slows
  // the scroll. The "see all" overflow can come later.
  const sliced = folderEntry.assets.slice(0, 12);
  const layout = scatter(hashSeed(meta.slug), sliced.length, {
    bounds: { minX: 16, maxX: 84, minY: 28, maxY: 82 },
    size: { min: 13, max: 19 },
    maxRot: 8,
  });
  const assets: BoardAsset[] = sliced.map((a, i) => ({ ...a, ...layout[i] }));
  return { ...meta, folder: folderEntry.folder, num, assets };
}

export const PROJECTS: Project[] = PROJECT_FOLDERS
  .map(buildProject)
  .sort((a, b) => a.num - b.num);

export function findBySlug(slug: string): Project | undefined {
  return PROJECTS.find((p) => p.slug === slug);
}
